name: Goods Wise Backend Deploy Production

on:
  push:
    branches:
      - 'master'

env:
  AWS_REGION: us-east-1 

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      STAGE: prod

    # Required for GitHub OIDC
    permissions:
      id-token: write
      contents: read

    steps:
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Print versions
        run: |
          node -v
          npm -v

      - name: Install Lambda packages dependencies
        working-directory: backend
        run: npm install && npm run build

      - name: Install dependencies
        working-directory: infra
        run: npm install

      - name: Debug GitHub context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Event: $GITHUB_EVENT_NAME"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::814203451617:role/goods-wise-backend-deploy-prod
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Deploy to Production
        working-directory: infra
        run: npx cdk deploy --require-approval never --all --context stage=prod
